language: r
r:
  - release
  - devel

sudo: false
cache: packages

warnings_are_errors: true

addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - devtools

notifications:
  slack: endtoendprovenance:DNYqXZWhV1c3eRhkjGYyjCEv
